export const STEP_WELCOME = 1;
export const STEP_REGISTER = 2;
export const STEP_TERMS = 3;
export const STEP_COMPANY = 4;
export const STEP_CATEGORIES = 5;
export const STEP_PLANS = 6;
export const STEP_THEMES = 7;
export const STEP_AI = 8;
export const STEP_SUMMARY = 9;
export const THEME_BASE_ID = 15; // id de las plantillas en general ecommerce
export const PLAN_BASE_ID = 25; // id de categoria que tiene los planes
export const STEP_NAME_REGISTER = 'admin_organization_wizard_register';
export const STEP_NAME_TERMS = 'admin_organization_wizard_terms';
export const STEP_NAME_COMPANY = 'admin_organization_wizard_organization';
export const STEP_NAME_CATEGORIES = 'admin_organization_wizard_category';
export const STEP_NAME_THEMES = 'admin_organization_wizard_theme';
export const STEP_NAME_PLANS = 'admin_organization_wizard_plan';
export const STEP_NAME_WELCOME = 'admin_organization_wizard_welcome';
export const STEP_NAME_SUMMARY = 'admin_organization_wizard_summary';
export const STEP_NAME_AI = 'admin_organization_wizard_ai';
export const LIMIT_PAGE = 30;
export const FORM_NAME = 'tenant-ia';

