export const STEP_REGISTER = 1;
export const STEP_TERMS = 2;
export const STEP_COMPANY = 3;
export const STEP_CATEGORIES = 4;
export const STEP_THEMES = 5;
export const STEP_PLANS = 6;
export const THEME_BASE_ID = 15; // id de las plantillas en general
export const PLAN_BASE_ID = 25; // id de categoria que tiene los planes
export const CATEGORY_ECOMMERCE_ID = 16; // id de categoria con plan ecommerce