export default {
    "data": [
		{
			"createdAt": "2023-05-08 16:29:40",
			"createdBy": 1,
			"deletedAt": null,
			"deletedBy": null,
			"id": 219,
			"key": "Update Data",
			"newValue": "{\"id\":111,\"is_home\":false,\"template\":\"default\",\"internal\":null,\"type\":null,\"system_name\":\"test\",\"record_type\":null,\"created_at\":\"2023-04-26T22:53:11.000000Z\",\"updated_at\":\"2023-04-26T22:53:11.000000Z\",\"options\":null,\"deleted_at\":null,\"created_by\":1,\"updated_by\":1,\"deleted_by\":null,\"organization_id\":null,\"page_id\":111,\"title\":\"Test 2\",\"slug\":\"test\",\"status\":true,\"body\":\"<p>Test<\\\/p>\",\"meta_title\":null,\"meta_description\":null,\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"content\":null,\"fields\":[{\"id\":190,\"name\":\"user_id\",\"type\":null,\"entity_id\":111,\"entity_type\":\"Modules\\\\Page\\\\Entities\\\\Page\",\"created_at\":\"2023-04-26T22:53:11.000000Z\",\"updated_at\":\"2023-04-26T22:53:11.000000Z\",\"deleted_at\":null,\"created_by\":1,\"updated_by\":1,\"deleted_by\":null,\"organization_id\":null,\"value\":1,\"translations\":[{\"id\":192,\"value\":1,\"field_id\":190,\"locale\":\"es\"}]},{\"id\":191,\"name\":\"medias_multi\",\"type\":null,\"entity_id\":111,\"entity_type\":\"Modules\\\\Page\\\\Entities\\\\Page\",\"created_at\":\"2023-05-02T16:51:01.000000Z\",\"updated_at\":\"2023-05-02T16:51:01.000000Z\",\"deleted_at\":null,\"created_by\":1,\"updated_by\":1,\"deleted_by\":null,\"organization_id\":null,\"value\":{\"gallery\":{\"files\":[177,176],\"orders\":\"177,176\"}},\"translations\":[{\"id\":193,\"value\":{\"gallery\":{\"files\":[177,176],\"orders\":\"177,176\"}},\"field_id\":191,\"locale\":\"es\"}]}],\"translations\":[{\"id\":217,\"page_id\":111,\"locale\":\"es\",\"title\":\"Test 2\",\"slug\":\"test\",\"status\":true,\"body\":\"<p>Test<\\\/p>\",\"meta_title\":null,\"meta_description\":null,\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"created_at\":\"2023-04-26T22:53:11.000000Z\",\"updated_at\":\"2023-05-08T21:06:13.000000Z\",\"organization_id\":null}]}",
			"oldValue": "{\"id\":111,\"is_home\":false,\"template\":\"default\",\"internal\":null,\"type\":null,\"system_name\":\"test\",\"record_type\":null,\"created_at\":\"2023-04-26T22:53:11.000000Z\",\"updated_at\":\"2023-04-26T22:53:11.000000Z\",\"options\":null,\"deleted_at\":null,\"created_by\":1,\"updated_by\":1,\"deleted_by\":null,\"organization_id\":null,\"page_id\":111,\"title\":\"Test 1\",\"slug\":\"test\",\"status\":true,\"body\":\"<p>Test<\\\/p>\",\"meta_title\":null,\"meta_description\":null,\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"content\":null,\"fields\":[{\"id\":190,\"name\":\"user_id\",\"type\":null,\"entity_id\":111,\"entity_type\":\"Modules\\\\Page\\\\Entities\\\\Page\",\"created_at\":\"2023-04-26T22:53:11.000000Z\",\"updated_at\":\"2023-04-26T22:53:11.000000Z\",\"deleted_at\":null,\"created_by\":1,\"updated_by\":1,\"deleted_by\":null,\"organization_id\":null,\"value\":1,\"translations\":[{\"id\":192,\"value\":1,\"field_id\":190,\"locale\":\"es\"}]},{\"id\":191,\"name\":\"medias_multi\",\"type\":null,\"entity_id\":111,\"entity_type\":\"Modules\\\\Page\\\\Entities\\\\Page\",\"created_at\":\"2023-05-02T16:51:01.000000Z\",\"updated_at\":\"2023-05-02T16:51:01.000000Z\",\"deleted_at\":null,\"created_by\":1,\"updated_by\":1,\"deleted_by\":null,\"organization_id\":null,\"value\":{\"gallery\":{\"files\":[177,176],\"orders\":\"177,176\"}},\"translations\":[{\"id\":193,\"value\":{\"gallery\":{\"files\":[177,176],\"orders\":\"177,176\"}},\"field_id\":191,\"locale\":\"es\"}]}],\"translations\":[{\"id\":217,\"page_id\":111,\"locale\":\"es\",\"title\":\"Test 1\",\"slug\":\"test\",\"status\":true,\"body\":\"<p>Test<\\\/p>\",\"meta_title\":null,\"meta_description\":null,\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"created_at\":\"2023-04-26T22:53:11.000000Z\",\"updated_at\":\"2023-05-08T21:06:13.000000Z\",\"organization_id\":null}]}",
			"organizationId": null,
			"revisionableId": 111,
			"revisionableType": "Modules\\Page\\Entities\\Page",
			"updatedAt": "2023-05-08 16:29:40",
			"updatedBy": 1
		},
		{
			"createdAt": "2023-05-08 16:06:55",
			"createdBy": 1,
			"deletedAt": null,
			"deletedBy": null,
			"id": 218,
			"key": "Update Data",
			"newValue": "{\"id\":111,\"is_home\":false,\"template\":\"default\",\"internal\":null,\"type\":null,\"system_name\":\"test\",\"record_type\":null,\"created_at\":\"2023-04-26T22:53:11.000000Z\",\"updated_at\":\"2023-04-26T22:53:11.000000Z\",\"options\":null,\"deleted_at\":null,\"created_by\":1,\"updated_by\":1,\"deleted_by\":null,\"organization_id\":null,\"page_id\":111,\"title\":\"Test 1\",\"slug\":\"test\",\"status\":true,\"body\":\"<p>Test<\\\/p>\",\"meta_title\":null,\"meta_description\":null,\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"content\":null,\"fields\":[{\"id\":190,\"name\":\"user_id\",\"type\":null,\"entity_id\":111,\"entity_type\":\"Modules\\\\Page\\\\Entities\\\\Page\",\"created_at\":\"2023-04-26T22:53:11.000000Z\",\"updated_at\":\"2023-04-26T22:53:11.000000Z\",\"deleted_at\":null,\"created_by\":1,\"updated_by\":1,\"deleted_by\":null,\"organization_id\":null,\"value\":1,\"translations\":[{\"id\":192,\"value\":1,\"field_id\":190,\"locale\":\"es\"}]},{\"id\":191,\"name\":\"medias_multi\",\"type\":null,\"entity_id\":111,\"entity_type\":\"Modules\\\\Page\\\\Entities\\\\Page\",\"created_at\":\"2023-05-02T16:51:01.000000Z\",\"updated_at\":\"2023-05-02T16:51:01.000000Z\",\"deleted_at\":null,\"created_by\":1,\"updated_by\":1,\"deleted_by\":null,\"organization_id\":null,\"value\":{\"gallery\":{\"files\":[177,176],\"orders\":\"177,176\"}},\"translations\":[{\"id\":193,\"value\":{\"gallery\":{\"files\":[177,176],\"orders\":\"177,176\"}},\"field_id\":191,\"locale\":\"es\"}]}],\"translations\":[{\"id\":217,\"page_id\":111,\"locale\":\"es\",\"title\":\"Test 1\",\"slug\":\"test\",\"status\":true,\"body\":\"<p>Test<\\\/p>\",\"meta_title\":null,\"meta_description\":null,\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"created_at\":\"2023-04-26T22:53:11.000000Z\",\"updated_at\":\"2023-05-08T21:06:13.000000Z\",\"organization_id\":null}]}",
			"oldValue": "{\"id\":1,\"is_home\":true,\"template\":\"default\",\"internal\":null,\"type\":null,\"system_name\":null,\"record_type\":null,\"created_at\":\"2020-09-18T02:34:40.000000Z\",\"updated_at\":\"2020-10-14T19:38:32.000000Z\",\"options\":null,\"deleted_at\":null,\"created_by\":null,\"updated_by\":null,\"deleted_by\":null,\"organization_id\":null,\"page_id\":1,\"title\":\"Inicio\",\"slug\":\"inicio\",\"status\":true,\"body\":\"<p>Somos especialistas en tu descanso, desarrollamos nuestra l&iacute;nea de colchones con la mejor calidad para que disfrutes tu descanso.<\\\/p>\",\"meta_title\":null,\"meta_description\":\"Somos especialistas en tu descanso, desarrollamos nuestra l\\u00ednea de colchones con la mejor calidad para que disfrutes tu descanso.\",\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"content\":null,\"fields\":[],\"translations\":[{\"id\":1,\"page_id\":1,\"locale\":\"en\",\"title\":\"Home page\",\"slug\":\"home\",\"status\":true,\"body\":\"<p><strong>You made it!<\\\/strong><\\\/p>\\n<p>You&#39;ve installed AsgardCMS and are ready to proceed to the <a href=\\\"\\\/en\\\/backend\\\">administration area<\\\/a>.<\\\/p>\\n<h2>What&#39;s next ?<\\\/h2>\\n<p>Learn how you can develop modules for AsgardCMS by reading our <a href=\\\"https:\\\/\\\/github.com\\\/AsgardCms\\\/Documentation\\\">documentation<\\\/a>.<\\\/p>\\n\",\"meta_title\":\"Home page\",\"meta_description\":null,\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"created_at\":\"2020-09-18T02:34:40.000000Z\",\"updated_at\":\"2020-09-18T02:34:40.000000Z\",\"organization_id\":null},{\"id\":2,\"page_id\":1,\"locale\":\"es\",\"title\":\"Inicio\",\"slug\":\"inicio\",\"status\":true,\"body\":\"<p>Somos especialistas en tu descanso, desarrollamos nuestra l&iacute;nea de colchones con la mejor calidad para que disfrutes tu descanso.<\\\/p>\",\"meta_title\":null,\"meta_description\":\"Somos especialistas en tu descanso, desarrollamos nuestra l\\u00ednea de colchones con la mejor calidad para que disfrutes tu descanso.\",\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"created_at\":\"2020-09-24T21:46:24.000000Z\",\"updated_at\":\"2021-07-28T02:35:23.000000Z\",\"organization_id\":null}]}",
			"organizationId": null,
			"revisionableId": 111,
			"revisionableType": "Modules\\Page\\Entities\\Page",
			"updatedAt": "2023-05-08 16:06:55",
			"updatedBy": 1
		},
		{
			"createdAt": "2023-05-08 16:06:13",
			"createdBy": 1,
			"deletedAt": null,
			"deletedBy": null,
			"id": 217,
			"key": "Update Data",
			"newValue": "{\"id\":111,\"is_home\":false,\"template\":\"default\",\"internal\":null,\"type\":null,\"system_name\":\"test\",\"record_type\":null,\"created_at\":\"2023-04-26T22:53:11.000000Z\",\"updated_at\":\"2023-04-26T22:53:11.000000Z\",\"options\":null,\"deleted_at\":null,\"created_by\":1,\"updated_by\":1,\"deleted_by\":null,\"organization_id\":null,\"page_id\":111,\"title\":\"Test 1\",\"slug\":\"test\",\"status\":true,\"body\":\"<p>Test<\\\/p>\",\"meta_title\":null,\"meta_description\":null,\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"content\":null,\"fields\":[{\"id\":190,\"name\":\"user_id\",\"type\":null,\"entity_id\":111,\"entity_type\":\"Modules\\\\Page\\\\Entities\\\\Page\",\"created_at\":\"2023-04-26T22:53:11.000000Z\",\"updated_at\":\"2023-04-26T22:53:11.000000Z\",\"deleted_at\":null,\"created_by\":1,\"updated_by\":1,\"deleted_by\":null,\"organization_id\":null,\"value\":1,\"translations\":[{\"id\":192,\"value\":1,\"field_id\":190,\"locale\":\"es\"}]},{\"id\":191,\"name\":\"medias_multi\",\"type\":null,\"entity_id\":111,\"entity_type\":\"Modules\\\\Page\\\\Entities\\\\Page\",\"created_at\":\"2023-05-02T16:51:01.000000Z\",\"updated_at\":\"2023-05-02T16:51:01.000000Z\",\"deleted_at\":null,\"created_by\":1,\"updated_by\":1,\"deleted_by\":null,\"organization_id\":null,\"value\":{\"gallery\":{\"files\":[177,176],\"orders\":\"177,176\"}},\"translations\":[{\"id\":193,\"value\":{\"gallery\":{\"files\":[177,176],\"orders\":\"177,176\"}},\"field_id\":191,\"locale\":\"es\"}]}],\"translations\":[{\"id\":217,\"page_id\":111,\"locale\":\"es\",\"title\":\"Test 1\",\"slug\":\"test\",\"status\":true,\"body\":\"<p>Test<\\\/p>\",\"meta_title\":null,\"meta_description\":null,\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"created_at\":\"2023-04-26T22:53:11.000000Z\",\"updated_at\":\"2023-04-26T22:53:11.000000Z\",\"organization_id\":null}]}",
			"oldValue": "{\"id\":1,\"is_home\":true,\"template\":\"default\",\"internal\":null,\"type\":null,\"system_name\":null,\"record_type\":null,\"created_at\":\"2020-09-18T02:34:40.000000Z\",\"updated_at\":\"2020-10-14T19:38:32.000000Z\",\"options\":null,\"deleted_at\":null,\"created_by\":null,\"updated_by\":null,\"deleted_by\":null,\"organization_id\":null,\"page_id\":1,\"title\":\"Inicio\",\"slug\":\"inicio\",\"status\":true,\"body\":\"<p>Somos especialistas en tu descanso, desarrollamos nuestra l&iacute;nea de colchones con la mejor calidad para que disfrutes tu descanso.<\\\/p>\",\"meta_title\":null,\"meta_description\":\"Somos especialistas en tu descanso, desarrollamos nuestra l\\u00ednea de colchones con la mejor calidad para que disfrutes tu descanso.\",\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"content\":null,\"fields\":[],\"translations\":[{\"id\":1,\"page_id\":1,\"locale\":\"en\",\"title\":\"Home page\",\"slug\":\"home\",\"status\":true,\"body\":\"<p><strong>You made it!<\\\/strong><\\\/p>\\n<p>You&#39;ve installed AsgardCMS and are ready to proceed to the <a href=\\\"\\\/en\\\/backend\\\">administration area<\\\/a>.<\\\/p>\\n<h2>What&#39;s next ?<\\\/h2>\\n<p>Learn how you can develop modules for AsgardCMS by reading our <a href=\\\"https:\\\/\\\/github.com\\\/AsgardCms\\\/Documentation\\\">documentation<\\\/a>.<\\\/p>\\n\",\"meta_title\":\"Home page\",\"meta_description\":null,\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"created_at\":\"2020-09-18T02:34:40.000000Z\",\"updated_at\":\"2020-09-18T02:34:40.000000Z\",\"organization_id\":null},{\"id\":2,\"page_id\":1,\"locale\":\"es\",\"title\":\"Inicio\",\"slug\":\"inicio\",\"status\":true,\"body\":\"<p>Somos especialistas en tu descanso, desarrollamos nuestra l&iacute;nea de colchones con la mejor calidad para que disfrutes tu descanso.<\\\/p>\",\"meta_title\":null,\"meta_description\":\"Somos especialistas en tu descanso, desarrollamos nuestra l\\u00ednea de colchones con la mejor calidad para que disfrutes tu descanso.\",\"og_title\":null,\"og_description\":null,\"og_image\":null,\"og_type\":null,\"created_at\":\"2020-09-24T21:46:24.000000Z\",\"updated_at\":\"2021-07-28T02:35:23.000000Z\",\"organization_id\":null}]}",
			"organizationId": null,
			"revisionableId": 111,
			"revisionableType": "Modules\\Page\\Entities\\Page",
			"updatedAt": "2023-05-08 16:06:13",
			"updatedBy": 1
		}
	],
    "meta": {
		"page": {
			"total": 1500,
			"lastPage": 1,
			"perPage": 10,
			"currentPage": 1
		}
	},
}